version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://db:27017
      - REDIS_URI=redis://redis:6379
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mongodb_data:
  redis_data:
